name: kenlo_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_logger: ^4.0.8+8
  equatable: ^2.0.5
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  mobx: ^2.0.7

dev_dependencies:
  json_serializable: ^6.2.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.11
  modular_test: ^2.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true
